# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea960331f9c12dcafc08d0bfc17845e46e4f83253ae15c9a63375c6ee04114b677ff9600fa61d79217f4eb48ba1b87ed1b831ef6354a766b71ae9b9b050ce3e

test:
  secret_key_base: 8c60e67f0563763a8bfb9bbcda16cee50aff62d02f050127c90554ed869f7bcf5b4c0ce4355b684c23ef922f1ab3bf2bf8e60ff9bec7aa14fd8f84bd0861dd9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
